# Generated by Django 3.1.6 on 2021-03-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordprofile',
            name='middlename',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='middlename',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
