# Generated by Django 3.1.6 on 2021-02-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('property', '0006_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.landlordprofile'),
        ),
    ]
