# Generated by Django 3.1.6 on 2021-05-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_field',
            new_name='image',
        ),
    ]
