# Generated by Django 3.1.6 on 2021-03-10 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_property_landlord'),
        ('users', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordreview',
            name='review_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='landlordreview',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tenantprofile'),
        ),
        migrations.AddField(
            model_name='tenantreview',
            name='review_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tenantprofile'),
        ),
        migrations.AddField(
            model_name='tenantreview',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
    ]
