# Generated by Django 3.1.6 on 2021-03-19 21:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20210312_2018'),
        ('users', '0001_initial'),
        ('reviews', '0002_auto_20210313_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewOnLandlordProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tenantprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewOnTenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tenantprofile')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tenantreview',
            name='review_on',
        ),
        migrations.RemoveField(
            model_name='tenantreview',
            name='reviewer',
        ),
        migrations.DeleteModel(
            name='LandlordReview',
        ),
        migrations.DeleteModel(
            name='TenantReview',
        ),
    ]
