# Generated by Django 3.1.6 on 2021-03-03 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_landlord'),
        ('reviews', '0002_auto_20210228_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordreview',
            name='review_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AlterField(
            model_name='tenantreview',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
    ]
