# Generated by Django 3.1.6 on 2021-02-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20210222_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='city',
        ),
    ]
