# Generated by Django 3.1.6 on 2021-03-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='region',
            name='included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subregion',
            name='included',
            field=models.BooleanField(default=False),
        ),
    ]
