# Generated by Django 3.1.6 on 2021-03-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20210305_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='included',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='included',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='included',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='subregion',
            old_name='included',
            new_name='enabled',
        ),
    ]
