# Generated by Django 3.1.6 on 2021-03-10 08:39

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20210310_0835'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='city',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='country',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='region',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='subregion',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
