# Generated by Django 3.1.6 on 2021-03-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_property_landlord'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='city',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='country',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='region',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='subregion',
            managers=[
            ],
        ),
    ]
