# Generated by Django 3.1.6 on 2021-03-12 20:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20210312_2018'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='city',
            managers=[
                ('included_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='country',
            managers=[
                ('included_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='region',
            managers=[
                ('included_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='subregion',
            managers=[
                ('included_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
