# Generated by Django 3.1.6 on 2021-05-10 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20210510_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='type',
            new_name='building_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
    ]
