# Generated by Django 3.1.6 on 2021-05-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20210517_1736'),
        ('property', '0016_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ManyToManyField(related_name='properties', to='images.Image'),
        ),
    ]
