# Generated by Django 3.1.6 on 2021-05-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_property_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='album',
        ),
    ]
