# Generated by Django 3.1.6 on 2021-05-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20210517_1736'),
        ('property', '0018_remove_property_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='properties', to='images.Image'),
        ),
    ]
