# Generated by Django 3.1.6 on 2021-03-17 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.ImageField(choices=[(1, 'Reviewnotification'), (2, 'Tenantratingnotification')], upload_to='')),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='notifications.notificationcontent')),
            ],
        ),
    ]
