# Generated by Django 3.1.6 on 2021-03-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(0, 'Empty'), (1, 'ReviewNotification'), (2, 'TenantRatingNotification')], default=0),
        ),
    ]
