# Generated by Django 3.1.6 on 2021-03-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210317_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Empty'), (1, 'ReviewNotification'), (2, 'TenantRatingNotification')], default=0, null=True)),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notificationtemplate'),
        ),
    ]
