# Generated by Django 3.1.6 on 2021-03-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210325_1257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationContent',
        ),
    ]
