# Generated by Django 3.1.6 on 2021-03-25 13:09

from django.db import migrations
from ..models import NotificationType


def create_templates(apps, schema_editor):
    NotificationTemplate = apps.get_model("notifications", "NotificationTemplate")
    db_alias = schema_editor.connection.alias
    NotificationTemplate.objects.using(db_alias).bulk_create([
        NotificationTemplate(type=NotificationType.REVIEW, subject='Review'),
        NotificationTemplate(type=NotificationType.RATING, subject='Rating'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_delete_notificationcontent'),
    ]

    operations = [
        migrations.RunPython(create_templates),
    ]
