# Generated by Django 3.1.6 on 2021-04-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_delete_notificationcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.IntegerField(choices=[(0, 'Empty'), (1, 'ReviewNotification'), (2, 'TenantRatingNotification')], default=0),
        ),
    ]
