# Generated by Django 3.1.6 on 2021-04-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20210402_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'ReviewNotification'), (2, 'TenantRatingNotification')]),
        ),
    ]
