# Generated by Django 3.1.6 on 2021-04-02 09:03

from django.db import migrations
from ..models import NotificationType


def create_templates(apps, schema_editor):
    NotificationTemplate = apps.get_model("notifications", "NotificationTemplate")
    db_alias = schema_editor.connection.alias
    NotificationTemplate.objects.using(db_alias).bulk_create([
        NotificationTemplate(type=NotificationType.REVIEW, subject='Review'),
        NotificationTemplate(type=NotificationType.RATING, subject='Rating'),
    ])


def delete_templates(apps, schema_editor):
    NotificationTemplate = apps.get_model("notifications", "NotificationTemplate")
    db_alias = schema_editor.connection.alias
    NotificationTemplate.objects.using(db_alias).filter(type=NotificationType.REVIEW, subject='Review').delete()
    NotificationTemplate.objects.using(db_alias).filter(type=NotificationType.RATING, subject='Rating').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0007_auto_20210402_0858'),
    ]

    operations = [
        migrations.RunPython(create_templates, delete_templates),
    ]
