# Generated by Django 3.1.6 on 2021-04-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_notification_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='receiver_user',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
