# Generated by Django 3.1.6 on 2021-04-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_notification_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='receiver',
            new_name='receiver_user',
        ),
    ]
